version: AppVeyor {branch} Build {build}

branches:
  except:
    - gh-pages
    
# fetch repository as zip archive
shallow_clone: true
    
# Do not build on tags (GitHub only)
skip_tags: true

platform: Any CPU
configuration: Release

build:
  project: Duality.sln
  verbosity: minimal
  
test:
  assemblies:
    - 'UnitTesting\DualityTests\**\*.dll'
  categories:
    only:
      - None   # AppVeyor VMs don't have GPU access and v1.x isn't able to deal with this at all.
