version: AppVeyor {branch} Build {build}

branches:
  except:
    - gh-pages
    
# Do not build on tags (GitHub only)
skip_tags: true

build:
  project: Duality.sln
  verbosity: minimal
  
test:
  assemblies:
  categories:
    only:
      - None   # AppVeyor VMs don't have GPU access and v1.x isn't able to deal with this at all.
