version: AppVeyor {branch} Build {build}

branches:
  except:
    - gh-pages
    
# Do not build on tags (GitHub only)
skip_tags: true

platform: Any CPU
configuration: Release

build:
  project: Duality.sln
  verbosity: minimal
  
test:
  assemblies:
    - 'UnitTesting\DualityTests\**\*.dll'
  categories:
    except:
      - Rendering   # AppVeyor VMs don't have GPU access.
  
after_test: '"Other\Scripts\Package Binary CI Script.bat"'

artifacts:
  - path: 'Other\NightlyBuild\Package\Duality.zip'
    name: "Binary Release"
  - path: 'Other\NightlyBuild\NuGetPackages'
    name: "All NuGet Packages"
# - path: 'Other\NightlyBuild\NuGetPackages\*.nupkg'
#   name: "NuGet Packages"
